window.config = {
	extension_sources: {
		GitCode: "https://raw.gitcode.com/RancherJie/noname_xingbei_extension/raw/master/",
		GitHub: "https://raw.githubusercontent.com/RancherJie/noname_xingbei_extension/master/",
	},
	extension_source: "GitCode",
	forbidai: [],
	forbidai_user: [],
	forbidall: [],
	forbidstone: [],
	forbidchess: [],
	forbidboss: [],
	forbiddouble: [],
	forbidthreecard: [],
	zhinang_tricks: [],
	connect_zhinang_tricks: [],
	all:{
		sgscharacters:['shiZhouNian'],
		sgscards:['xingBei'],
		sgsmodes:['connect','xingBei'],
		stockmode:['connect','xingBei','offlineChoose','illustration','tutorial','leaderboard','boss'],
		nogamemode:['connect','illustration','tutorial','leaderboard'],
		stockextension:[],
		layout:['default','newlayout'],
		theme:['woodden','music','simple'],
		card_font:['xiaozhuan','huangcao','caoshu','xingshu'],
		double_hp:['hejiansan','pingjun','zuidazhi','zuixiaozhi','zonghe'],
		image_background_filter:['default','blur','gray','sepia','invert','saturate','contrast','hue','brightness'],
	},

	game: "sgs",
	duration: 500,
	hoveration: 1000,
	doubleclick_intro: true,
	cheat: false,
	volumn_background: 0,
	volumn_audio: 0,

	connect_avatar: "fengZhiJianSheng",
	connect_nickname: "無",
	connect_profile_initialized: false,
	config_menu: true,
	auto_popped_config: true,
	auto_popped_history: false,
	auto_skill: true,
	auto_confirm: true,
	enable_drag: true,
	enable_pressure: false,
	pressure_taptic: true,
	hover_handcard: true,
	hover_all: true,
	right_info: true,
	longpress_info: true,
	long_info: true,
	background_music: "music_off",
	background_audio: false,
	background_speak: false,
	glow_phase: "yellow",
	die_move: "flip",
	link_style2:'rotate',

	skin: {},
	gameRecord: {},
	extensionInfo: {},
	autoskilllist: [],
	hiddenModePack: [],
	hiddenCharacterPack: [],
	hiddenCardPack: [],
	hiddenPlayPack: [],
	hiddenBackgroundPack: [],
	customBackgroundPack: [],
	favouriteCharacter: [],
	favouriteMode: [],
	recentIP: [],
	vintageSkills: [],
	alteredSkills: [],
	brokenFile: [],

	theme: "music",
	layout: "nova",
	card_style: "default",
	cardback_style: "xingBei",
	hp_style: "xingBei",

	image_character: "default",
	image_background: "default",

	asset_image: true,
	asset_font: true,

	card_font: "xiaozhuan",
	show_statusbar_ios: "off",
	show_statusbar_android: false,
	show_name: true,
	show_replay: false,
	show_round_menu: true,
	show_pause: true,
	show_auto: true,
	show_volumn: true,
	show_cardpile: true,
	only_fullskin: true,
	show_connect: true,
	show_wuxie: false,
	show_wuxie_self: true,
	show_stat: true,
	show_playerids: true,
	show_scrollbar: false,
	mousewheel: true,
	fold_card: true,
	threed_card: false,
	vertical_scroll: false,
	handcard_scroll: 0,
	animation: true,
	skill_animation_type: "default",
	paused: false,
	title: false,
	button_press: true,
	damage_shake: true,
	log_highlight: true,
	player_border: "normal",
	radius_size: "default",

	modeconfig: false,
	gameconfig: false,
	appearence: false,
	video: "20",
	coin: 0,

	intro: "i",
	right_click: "pause",
	sort: "type_sort",

	cards: ["xingBei"],
	characters: ['shiZhouNian'],
	moderned_chracters: [],
	connect_characters: ['yiDuanYeHuo','shenZiChuangLin','sanBan','siBan','zhongMoDaoZhu','teDian','poXiao','boss'],//默認關閉的角色包
	connect_cards: [],
	plays: [],
	extensions: [],
	banned: [],
	bannedcards: [],
	forbidlist: [//互斥角色組合
		['hongLianQiShi','shengDianQiShi'],
		['shengNv','jinGuiZhiNv'],
		['fengZhiJianSheng','jianZhiZi'],
	],
	bannedpile: {},
	customcardpile: {},
	addedpile: {},

	mode: "tutorial",
	mode_config: {
		xingBei: {
			versus_mode: "three",
			team_sequence: "CM",
		},
	},
	current_mode: {},
	customforbid: [],
	forbid: [
		
	],
};
