const dictionary = {
	//無名殺自己的名詞
	用間: ["yòng jiàn"],
	//無名殺的人名
	樂進: ["yuè jìn"],
	樂就: ["yuè jiù"],
	樂綝: ["yuè chēn"],
	華歆: ["huà xīn"],
	華雄: ["huà xióng"],
	賈詡: ["jiǎ xǔ"],
	賈逵: ["jiǎ kuí"],
	賈充: ["jiǎ chōng"],
	沮授: ["jū shòu"],
	紀靈: ["jǐ líng"],
	笮融: ["zé róng"],
	逢紀: ["páng jì"],
	許褚: ["xǔ chǔ"],
	劉辟: ["liú pì"],
	劉禪: ["liú shàn"],
	甄宓: ["zhēn fú"],
	孫綝: ["sūn chēn"],
	李傕: ["lǐ jué"],
	李遺: ["lǐ wèi"],
	張嶷: ["zhāng nì"],
	蔣幹: ["jiǎng gàn"],
	雷薄: ["léi bó"],
	呂蒙: ["lǚ méng"],
	于禁: ["yú jìn"],
	趙累: ["zhào lèi"],
	夏侯令女: ["xià hóu lìng nǚ"],
	馬日磾: ["mǎ mì dī"],
	史阿: ["shǐ ē"],
	凱撒: ["kǎi sà"],
	樂無異: ["yuè wú yì"],
	端蒙: ["duān méng"],
	妹喜: ["mò xǐ"],
	洛歐塞布: ["luò ōu sài bù"],
	塞納留斯: ["sài nà liú sī"],
	半藏: ["bàn zàng"],
	地藏王: ["dì zàng wáng"],
	查莉婭: ["zhā lì yà"],
	單小小: ["shàn xiǎo xiǎo"],
	少微: ["shào wēi"],
	少昊: ["shào hào"],
	歐陽少恭: ["ōu yáng shào gōng"],
	卡爾維特: ["kǎ ěr wéi tè"],
	卡西爾: ["kǎ xī ěr"],
	卡扎庫斯: ["kǎ zā kù sī"],
	卡德加: ["kǎ dé jiā"],
	法蘭茜斯卡: ["fǎ lán qiàn sī kǎ"],
	卡利莫斯: ["kǎ lì mò sī"],
	安卡: ["ān kǎ"],
	卡瑪: ["kǎ mǎ"],
	檮杌: ["táo wù"],
	亞煞極: ["yà shà jí"],
	庫特莉亞芙卡: ["kù tè lì yà fú kǎ"],
	露娜: ["lù nà"],
	//無名殺自己的技能
	彈雀: ["tán què"],
	重身: ["chóng shēn"],
	畜鳴: ["chù míng"],
	聆樂: ["líng yuè"],
	沒矢: ["mò shǐ"],
	沒欲: ["mò yù"],
	血裔: ["xuè yì"],
	血衛: ["xuè wèi"],
	血詔: ["xuè zhào"],
	血償: ["xuè cháng"],
	血拼: ["xuè pīn"],
	血途: ["xuè tú"],
	行殤: ["xíng shāng"],
	節行: ["jié xíng"],
	天行: ["tiān xíng"],
	神行: ["shén xíng"],
	鎮行: ["zhèn xíng"],
	行圖: ["xíng tú"],
	絕行: ["jué xíng"],
	好施: ["hào shī"],
	薦降: ["jiàn xiáng"],
	破降: ["pò xiáng"],
	拒降: ["jù xiáng"],
	應勢: ["yìng shì"],
	應援: ["yìng yuán"],
	應機: ["yìng jī"],
	節應: ["jié yìng"],
	馳應: ["chí yìng"],
	斷髮: ["duàn fà"],
	旋風: ["xuàn fēng"],
	將馳: ["jiàng chí"],
	將烈: ["jiàng liè"],
	將略: ["jiàng lüè"],
	斬將: ["zhǎn jiàng"],
	拜將: ["bài jiàng"],
	強識: ["qiáng zhì"],
	默識: ["mò zhì"],
	數諫: ["shuò jiàn"],
	巧說: ["qiǎo shuì"],
	營說: ["yíng shuì"],
	說盟: ["shuì méng"],
	落寵: ["luò chǒng"],
	落雁: ["luò yàn"],
	落雷: ["luò léi"],
	賁育: ["bēn yù"],
	造王: ["zào wàng"],
	舍宴: ["shě yàn"],
	舍裔: ["shě yì"],
	省身: ["xǐng shēn"],
	單騎: ["dān jì"],
	間書: ["jiàn shū"],
	伏間: ["fú jiàn"],
	間計: ["jiàn jì"],
	貴相: ["guì xiàng"],
	相鼠: ["xiàng shǔ"],
	闢田: ["pì tián"],
	闢撰: ["pì zhuàn"],
	闢境: ["pì jìng"],
	鬥陣: ["dòu zhèn"],
	鬥纏: ["dòu chán"],
	馮河: ["píng hé"],
	勢嚇: ["shì hè"],
	虛嚇: ["xū hè"],
	叱嚇: ["chì hè"],
	度斷: ["duó duàn"],
	度勢: ["duó shì"],
	誅綝: ["zhū chēn"],
	大喝: ["dà hè"],
	暴喝: ["bào hè"],
	曲誤: ["qǔ wù"],
	媛麗: ["yuán lì"],
	調歸: ["diào guī"],
	款塞: ["kuǎn sài"],
	父蔭: ["fù yìn"],
	穆蔭: ["mù yìn"],
	長姬: ["zhǎng jī"],
	朝鳳: ["cháo fèng"],
	朝爭: ["cháo zhēng"],
	令法: ["lìng fǎ"],
	耀令: ["yào lìng"],
	冠絕: ["guàn jué"],
	先著: ["xiān zhuó"],
	量反: ["liàng fǎn"],
	復難: ["fù nàn"],
	膴仕: ["wǔ shì"],
	蒙斥: ["méng chì"],
	樂動: ["yuè dòng"],
	血凰: ["xuè huáng"],
	血戮: ["xuè lù"],
	血刃: ["xuè rèn"],
	血契: ["xuè qì"],
	血逐: ["xuè zhú"],
	血咒: ["xuè zhòu"],
	血殤: ["xuè shāng"],
	血池: ["xuè chí"],
	越行: ["yuè xíng"],
	俠行: ["xiá xíng"],
	梟行: ["xiāo xíng"],
	劫行: ["jié xíng"],
	割發: ["gē fà"],
	落梅: ["luò méi"],
	落石: ["luò shí"],
	落刀: ["luò dāo"],
	星落: ["xīng luò"],
	奈落: ["nài luò"],
	捨身: ["shě shēn"],
	舍願: ["shě yuàn"],
	月露: ["yuè lù"],
	沾露: ["zhān lù"],
	禁咒: ["jìn zhòu"],
	挾令: ["xié lìng"],
	七煞: ["qī shà"],
	冥煞: ["míng shà"],
	虎煞: ["hǔ shà"],
	煞魂: ["shà hún"],
};

export default dictionary;
